// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: push_payload_v1.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// PushPayload — содержимое push-уведомления. По gRPC не ходит: сервер шифрует
/// его ключом сессии получателя и кладёт в поле `p` пуша (APNs — рядом с `aps`,
/// FCM — в data). Расшифровывает устройство (iOS — Notification Service
/// Extension, Android — FCM-сервис), Apple/Google содержимого не видят.
///
/// Формат `p` (base64 standard):
///   header = version(1 байт, =1) || session[0:8] || nonce(12)
///   key    = HKDF-SHA256(ikm = sharedKey, salt = sharedSalt, info = "iperon-push-v1"), 32 байта
///   p      = base64(header || AES-256-GCM(key, nonce, plaintext = PushPayload, aad = header))
/// session[0:8] — первые 8 байт 32-байтного идентификатора сессии (session.session
/// на клиенте): по нему устройство выбирает ключ (задел под несколько аккаунтов).
/// См. docs/plans/push-notifications.md.
nonisolated struct Iperon_V1_PushPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Iperon_V1_PushPayload.Kind = .unknown

  /// Идентификатор уведомления: им же помечается системное уведомление
  /// (iOS request identifier, Android tag) — повтор доставки заменяет, а не
  /// дублирует; по нему же уведомление потом снимают.
  var id: String = String()

  var fromUserID: Data = Data()

  var chatID: Data = Data()

  var messageID: Int64 = 0

  /// Готовый заголовок (имя отправителя: из облачного контакта, профиля или
  /// номер). Пусто — клиент подставит свой (например, для TEST).
  var title: String = String()

  /// Текст. Пусто — без превью (настройки/код-пароль) или текст строит клиент.
  var body: String = String()

  var args: [String] = []

  /// 0 — не трогать
  var badge: Int32 = 0

  /// unix millis события
  var date: Int64 = 0

  /// READ_HISTORY / MESSAGE_DELETED
  var messageIds: [Int64] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Kind: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case unknown // = 0

    /// тестовое (экран «Разработчик»), текст — на клиенте
    case test // = 1

    /// контакт из книги зарегистрировался
    case contactJoined // = 2

    /// пропущенный звонок (только iOS)
    case callMissed // = 3

    /// новое сообщение (этап 7)
    case message // = 10

    /// прочитано на другом устройстве — снять (тихий)
    case readHistory // = 11

    /// сообщения удалены — снять (тихий)
    case messageDeleted // = 12
    case UNRECOGNIZED(Int)

    init() {
      self = .unknown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .test
      case 2: self = .contactJoined
      case 3: self = .callMissed
      case 10: self = .message
      case 11: self = .readHistory
      case 12: self = .messageDeleted
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .test: return 1
      case .contactJoined: return 2
      case .callMissed: return 3
      case .message: return 10
      case .readHistory: return 11
      case .messageDeleted: return 12
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Iperon_V1_PushPayload.Kind] = [
      .unknown,
      .test,
      .contactJoined,
      .callMissed,
      .message,
      .readHistory,
      .messageDeleted,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "iperon.v1"

nonisolated extension Iperon_V1_PushPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PushPayload"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{1}id\0\u{1}fromUserID\0\u{1}chatID\0\u{1}messageID\0\u{1}title\0\u{1}body\0\u{1}args\0\u{1}badge\0\u{1}date\0\u{1}messageIDs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.fromUserID) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.chatID) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.messageID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.args) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.badge) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.date) }()
      case 11: try { try decoder.decodeRepeatedInt64Field(value: &self.messageIds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.kind != .unknown {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    if !self.fromUserID.isEmpty {
      try visitor.visitSingularBytesField(value: self.fromUserID, fieldNumber: 3)
    }
    if !self.chatID.isEmpty {
      try visitor.visitSingularBytesField(value: self.chatID, fieldNumber: 4)
    }
    if self.messageID != 0 {
      try visitor.visitSingularInt64Field(value: self.messageID, fieldNumber: 5)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 6)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 7)
    }
    if !self.args.isEmpty {
      try visitor.visitRepeatedStringField(value: self.args, fieldNumber: 8)
    }
    if self.badge != 0 {
      try visitor.visitSingularInt32Field(value: self.badge, fieldNumber: 9)
    }
    if self.date != 0 {
      try visitor.visitSingularInt64Field(value: self.date, fieldNumber: 10)
    }
    if !self.messageIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.messageIds, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Iperon_V1_PushPayload, rhs: Iperon_V1_PushPayload) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.id != rhs.id {return false}
    if lhs.fromUserID != rhs.fromUserID {return false}
    if lhs.chatID != rhs.chatID {return false}
    if lhs.messageID != rhs.messageID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.body != rhs.body {return false}
    if lhs.args != rhs.args {return false}
    if lhs.badge != rhs.badge {return false}
    if lhs.date != rhs.date {return false}
    if lhs.messageIds != rhs.messageIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Iperon_V1_PushPayload.Kind: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0\u{1}TEST\0\u{1}CONTACT_JOINED\0\u{1}CALL_MISSED\0\u{2}\u{7}MESSAGE\0\u{1}READ_HISTORY\0\u{1}MESSAGE_DELETED\0")
}
