syntax = "proto3";

package iperon.v1;
option go_package = "internal/api/v1";

import "google/protobuf/timestamp.proto";
import "protos/models.proto";


message MyProfile {
  message Request {}

  message Response {
    optional string firstName = 1;
    optional string lastName = 2;
    optional string aboutMe = 4;
    optional google.protobuf.Timestamp birthDate = 3;
    optional CDN avatar = 5;
  }
}

message MyProfileUpdate {
  message Request {
    optional string firstName = 1;
    optional string lastName = 2;
    optional string aboutMe = 4;
    optional google.protobuf.Timestamp birthDate = 3;
  }

  message Response {
  }
}

message MyProfileAvatarUpdate {
  message Request {
    optional bytes avatar = 1;
  }

  message Response {
    optional CDN avatar = 1;
  }
}
