syntax = "proto3";

package v1;
option go_package = "internal/api/v1";

import "google/protobuf/timestamp.proto";

enum MessageType {
  HEALTHCHECK = 0;
  META_DATA_INFO = 1;
  AUTH_CALL_PASSWORD = 2;
  AUTH_CALL_PASSWORD_CONFIRMATION = 3;
  AUTH_MODERATION_APPLICATION_STORE = 4;
  AUTH_MODERATION_APPLICATION_STORE_CONFIRMATION = 5;
  DEVICE_SESSIONS = 6;
  LOGOUT = 7;
  SUBSCRIBE = 8;
  DEVICE_SESSIONS_TERMINATE = 9;
  AUTH_CONFIRMATION = 10;
  MY_PROFILE = 11;
  MY_PROFILE_UPDATE = 12;
  DEVICE_INFO_UPDATE = 13;
  MY_PROFILE_AVATAR_UPDATE = 14;
  UPLOAD_CONFIRM = 15;
  CALL_OFFER = 16;
  CALL_ANSWER = 17;
  CALL_ICE_CANDIDATE = 18;
  CALL_HANGUP = 19;
  CALL_REJECT = 20;
  CALL_ICE_SERVERS = 21;
  MY_PROFILE_USERNAME_UPDATE = 22;
  PROFILE = 23;
  CONTACTS_DISCOVERY_EVALUATE = 24;
  CONTACTS_DISCOVERY_MATCH = 25;
  REGISTER_PUSH_TOKEN = 26;
  CALL_TOKEN = 27;
}

service Iperon {
  rpc Unary (Message) returns (Message) {}
  rpc Stream (stream Message) returns (stream Message) {}
  rpc Upload (stream Upload.Request) returns (stream Upload.Response) {}
}

// Messages
message Message {
  MessageType messageType = 1;
  bytes message = 2;
  google.protobuf.Timestamp currentAt = 3;
}

// Upload (media files)
message Upload {
  message Init {
    string sessionId = 1;
    int64 fileSize = 2;
    optional string resumeUploadId = 3;
  }

  message Chunk {
    bytes data = 1;
  }

  message Done {
  }

  message InitAck {
    string uploadId = 1;
    int64 receivedBytes = 2;
  }

  message ChunkAck {
    int64 receivedBytes = 1;
  }

  message CompleteAck {
    string uploadId = 1;
    int64 receivedBytes = 2;
  }

  message Request {
    oneof payload {
      Init init = 1;
      Chunk chunk = 2;
      Done done = 3;
    }

  }

  message Response {
    oneof payload {
      InitAck initAck = 1;
      ChunkAck chunkAck = 2;
      CompleteAck completeAck = 3;
    }
  }
}
