name: Test Flight

on:
  pull_request:
  push:
    branches: [main]

jobs:
  Linter:
    uses: iperon-net/messenger/.github/workflows/_linter.yaml@main
    with:
      flutter_version: "3.47.1"
    secrets:
      firebase_options_dart_base64: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64 }}


#  DeployTestFlight:
#    uses: iperon-net/messenger/.github/workflows/_deploy_testflight.yaml@main
#    secrets: [FLUTTER_API_KEY, APPLE_API_KEY]
